import{a as $,S as q,i as p}from"./assets/vendor-c493984e.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const I="https://pixabay.com/api/";async function P(e,s=1){const a=new URLSearchParams({key:"43854532-e18365a3905b9485abf8e557c",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s});return(await $.get(`${I}?${a}`)).data}const y=document.querySelector(".gallery"),d=document.querySelector(".loader"),i=document.querySelector(".more-btn");let h=0,c=1,L="",m=0;const g=15,E=new q(".gallery a",{captionsData:"alt",captionDelay:250});async function O(e){e.preventDefault();const s=e.target.search.value.trim();if(!s){w("The field cannot be empty!");return}L=s,c=1,e.target.search.value="",l(d),y.innerHTML="",b()}async function b(){l(d),u(i);try{const e=await P(L,c);if(h=e.totalHits,e.totalHits===0){f("Sorry, there are no images matching your search query. Please, try again!");return}H(e.hits)}catch(e){console.log(e),f("Oops, something went wrong. Please, try again later!")}finally{u(d)}}async function D(){c+=1,b()}function H(e){const s=e.map(({webformatURL:a,largeImageURL:o,tags:t,likes:r,views:n,comments:v,downloads:S})=>`<li class="gallery-item">
        <a href="${o}" class="gallery-item-link">
          <img src="${a}" alt="${t}" class="gallery-item-img" />
          <div class="gallery-item-content">
            <p class="gallery-item-descr">Likes<span>${r}</span></p>
            <p class="gallery-item-descr">Views<span>${n}</span></p>
            <p class="gallery-item-descr">Comments<span>${v}</span></p>
            <p class="gallery-item-descr">Donwloads<span>${S}</span></p>
          </div>
        </a>
      </li>`).join("");y.insertAdjacentHTML("beforeend",s),M(),E.refresh(),c*g>h?(u(i),w("We're sorry, but you've reached the end of search results.")):l(i),e.length<g?u(i):l(i)}function M(){const e=document.querySelector(".gallery-item");e&&(m=e.getBoundingClientRect().height,c>1&&setTimeout(()=>{window.scrollBy({top:m*2,behavior:"smooth"})},300))}function w(e){p.warning({message:e,position:"topRight"})}function f(e){p.error({message:e,position:"topRight"})}function l(e){e.classList.remove("is-hidden"),e.classList.add("is-active")}function u(e){e.classList.remove("is-active"),e.classList.add("is-hidden")}const B=document.querySelector(".form"),R=document.querySelector(".more-btn");B.addEventListener("submit",O);R.addEventListener("click",D);
//# sourceMappingURL=commonHelpers.js.map
